### ISSUE TITLE
Create all the content items (stories, links, dataset pages)

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-eic#7]
```[tasklist]
### Tasks
- [x] Theme intro stories
- [x] Theme feature stories / external links
- [x] Visit root page
- [x] Visit feature stories / external links
- [x] Teach root page
- [x] Teach feature stories / external links
```

**Comment by hanbyul-here** [comment]
Items to check in with EIC team
- Each theme page has repeating components, such as custom video players. 
  - Does this component already exist somewhere? (So we can embed this?)
  - If not, what needs to be created?

**Comment by agurvich** [comment]
@hanbyul-here are you referring to the video carousel with the arrows and thumbnails? That component does not currently exist, but I can contribute to creating/fully create one.

**Comment by j08lue** [comment]
I created a separate issue for the question of what to do about video carousels: https://github.com/NASA-IMPACT/veda-config-eic/issues/15

I think solving this nicely has very low priority compared to getting all the content in and we should just see whether there is at all time for this before Nov 17th. We can figure that out on the ticket.
